# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e54ba0d528a1ae94ceee4f808679a3e3f834f1db723e0b81902085730ba3ebe9d9a89a6ccbd8d596105158e29ebc4dd3b8d4dab50a6173c8e9d5ef93cbd9be

test:
  secret_key_base: 65dd7fdc41306ae4987aa988c5465aef0d3c8fb2359bfe9e4b6c5e5f72a3b5fc6da83c330b1217524c681c32cc457f63d756a4bdcaf575f227de23d0b7aadd1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
